//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebXemPhim.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class gioithieu
    {
        public int idgioitin { get; set; }
        public string noidung { get; set; }
        public string sdtlien { get; set; }
    }
}
