//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebXemPhim.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nam
    {
        public int MaNam { get; set; }
        public Nullable<int> TenNam { get; set; }
    }
}
