//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectQuanLyDoAnVat
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitiethoadon
    {
        public int id { get; set; }
        public int idhoadon { get; set; }
        public int idmonan { get; set; }
        public int count { get; set; }
    
        public virtual hoadon hoadon { get; set; }
        public virtual mon mon { get; set; }
    }
}
