//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectQuanLyDoAnVat
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Data_QLDAEntities : DbContext
    {
        public Data_QLDAEntities()
            : base("name=Data_QLDAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ban> ban { get; set; }
        public virtual DbSet<chitiethoadon> chitiethoadon { get; set; }
        public virtual DbSet<hoadon> hoadon { get; set; }
        public virtual DbSet<mon> mon { get; set; }
        public virtual DbSet<taikhoan> taikhoan { get; set; }
    }
}
