//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectQuanLyDoAnVat
{
    using System;
    using System.Collections.Generic;
    
    public partial class taikhoan
    {
        public string tennguoidung { get; set; }
        public string tengiaodien { get; set; }
        public string matkhau { get; set; }
        public int type { get; set; }
    }
}
